package com.cezarykluczynski.stapi.server.astronomicalObject.endpoint

import com.cezarykluczynski.stapi.server.series.common.AbstractEndpointIntegrationTest

abstract class AbstractAstronomicalObjectEndpointIntegrationTest extends AbstractEndpointIntegrationTest {
}
