swagger: '2.0'
info:
  title: STAPI
  version: '1.0.0'
host: stapi.co
schemes:
  - http
basePath: /api/v1/rest
produces:
  - application/json
paths:
  /character:
    $ref: ./character.paths.yaml
  /series:
    $ref: ./series.paths.yaml
  /performer:
    $ref: ./performer.paths.yaml
  /staff:
    $ref: ./staff.paths.yaml
definitions:
  Character:
    $ref: ./character.definitions.yaml
  CharacterHeader:
    $ref: ./characterHeader.definitions.yaml
  CharacterResponse:
    $ref: ./characterResponse.definitions.yaml
  Series:
    $ref: ./series.definitions.yaml
  SeriesResponse:
    $ref: ./seriesResponse.definitions.yaml
  Performer:
    $ref: ./performer.definitions.yaml
  PerformerHeader:
    $ref: ./performerHeader.definitions.yaml
  PerformerResponse:
    $ref: ./performerResponse.definitions.yaml
  Staff:
    $ref: ./staff.definitions.yaml
  StaffResponse:
    $ref: ./staffResponse.definitions.yaml
  Error:
    $ref: ./error.definitions.yaml
  ResponsePage:
    $ref: ./responsePage.definitions.yaml
