swagger: '2.0'
info:
  title: STAPI
  version: '1.0.0'
host: stapi.co
schemes:
  - http
basePath: /api/v1/rest
produces:
  - application/json
paths:
  /character:
    $ref: ./character/path/character.path.yaml
  /performer:
    $ref: ./performer/path/performer.path.yaml
  /series:
    $ref: ./series/path/series.path.yaml
  /staff:
    $ref: ./staff/path/staff.path.yaml
definitions:
  Character:
    $ref: ./character/entity/character.yaml
  CharacterHeader:
    $ref: ./character/entity/characterHeader.yaml
  CharacterResponse:
    $ref: ./character/entity/characterResponse.yaml
  Error:
    $ref: ./common/entity/error.yaml
  Performer:
    $ref: ./performer/entity/performer.yaml
  PerformerHeader:
    $ref: ./performer/entity/performerHeader.yaml
  PerformerResponse:
    $ref: ./performer/entity/performerResponse.yaml
  ResponsePage:
    $ref: ./common/entity/responsePage.yaml
  Series:
    $ref: ./series/entity/series.yaml
  SeriesResponse:
    $ref: ./series/entity/seriesResponse.yaml
  Staff:
    $ref: ./staff/entity/staff.yaml
  StaffResponse:
    $ref: ./staff/entity/staffResponse.yaml
