swagger: '2.0'
info:
  title: STAPI
  version: '1.0.0'
host: stapi.co
schemes:
  - http
basePath: /api/v1/rest
produces:
  - application/json
paths:
  /character:
    $ref: ./path/character.path.yaml
  /performer:
    $ref: ./path/performer.path.yaml
  /series:
    $ref: ./path/series.path.yaml
  /staff:
    $ref: ./path/staff.path.yaml
definitions:
  Character:
    $ref: ./entity/character/character.yaml
  CharacterHeader:
    $ref: ./entity/character/characterHeader.yaml
  CharacterResponse:
    $ref: ./entity/character/characterResponse.yaml
  Error:
    $ref: ./entity/common/error.yaml
  Performer:
    $ref: ./entity/performer/performer.yaml
  PerformerHeader:
    $ref: ./entity/performer/performerHeader.yaml
  PerformerResponse:
    $ref: ./entity/performer/performerResponse.yaml
  ResponsePage:
    $ref: ./entity/common/responsePage.yaml
  Series:
    $ref: ./entity/series/series.yaml
  SeriesResponse:
    $ref: ./entity/series/seriesResponse.yaml
  Staff:
    $ref: ./entity/staff/staff.yaml
  StaffResponse:
    $ref: ./entity/staff/staffResponse.yaml
