package com.cezarykluczynski.stapi.server.trading_card_deck.endpoint

import com.cezarykluczynski.stapi.server.series.common.AbstractEndpointIntegrationTest

abstract class AbstractTradingCardDeckEndpointIntegrationTest extends AbstractEndpointIntegrationTest {
}
