package com.cezarykluczynski.stapi.server.magazine_series.endpoint

import com.cezarykluczynski.stapi.server.series.common.AbstractEndpointIntegrationTest

abstract class AbstractMagazineSeriesEndpointIntegrationTest extends AbstractEndpointIntegrationTest {
}
