package com.cezarykluczynski.stapi.server.book_collection.endpoint

import com.cezarykluczynski.stapi.server.series.common.AbstractEndpointIntegrationTest

abstract class AbstractBookCollectionEndpointIntegrationTest extends AbstractEndpointIntegrationTest {
}
