package com.cezarykluczynski.stapi.server.book_collection.endpoint

import com.cezarykluczynski.stapi.server.common.endpoint.AbstractEndpointIntegrationTest

abstract class AbstractBookCollectionEndpointIntegrationTest extends AbstractEndpointIntegrationTest {
}
