package com.cezarykluczynski.stapi.server.spacecraft_class.endpoint

import com.cezarykluczynski.stapi.server.series.common.AbstractEndpointIntegrationTest

abstract class AbstractSpacecraftClassEndpointIntegrationTest extends AbstractEndpointIntegrationTest {
}
