package com.cezarykluczynski.stapi.server.trading_card_set.endpoint

import com.cezarykluczynski.stapi.server.common.endpoint.AbstractEndpointIntegrationTest

abstract class AbstractTradingCardSetEndpointIntegrationTest extends AbstractEndpointIntegrationTest {
}
