package com.cezarykluczynski.stapi.etl.template.planet.dto.enums;

public enum AstronomicalObjectType {

	PLANET,
	D_CLASS_PLANET,
	H_CLASS_PLANET,
	GAS_GIANT_PLANET,
	K_CLASS_PLANET,
	L_CLASS_PLANET,
	M_CLASS_PLANET,
	Y_CLASS_PLANET,
	ROGUE_PLANET,
	ARTIFICIAL_PLANET,
	ASTEROID,
	ASTEROIDAL_MOON,
	ASTEROID_BELT,
	CLUSTER,
	COMET,
	CONSTELLATION,
	GALAXY,
	MOON,
	M_CLASS_MOON,
	NEBULA,
	PLANETOID,
	D_CLASS_PLANETOID,
	QUASAR,
	STAR,
	STAR_SYSTEM,
	SECTOR,
	REGION
	// BINARY_STAR // TODO version 2
	// PROTOPLANET // TODO version 2

}
