package com.cezarykluczynski.stapi.server.astronomical_object.endpoint

import com.cezarykluczynski.stapi.server.series.common.AbstractEndpointIntegrationTest

abstract class AbstractAstronomicalObjectEndpointIntegrationTest extends AbstractEndpointIntegrationTest {
}
