package com.cezarykluczynski.stapi.server.astronomical_object.endpoint

import com.cezarykluczynski.stapi.server.common.endpoint.AbstractEndpointIntegrationTest

abstract class AbstractAstronomicalObjectEndpointIntegrationTest extends AbstractEndpointIntegrationTest {
}
