package com.cezarykluczynski.stapi.server.comic_collection.endpoint

import com.cezarykluczynski.stapi.server.common.endpoint.AbstractEndpointIntegrationTest

abstract class AbstractComicCollectionEndpointIntegrationTest extends AbstractEndpointIntegrationTest {
}
