package com.cezarykluczynski.stapi.server.comic_collection.endpoint

import com.cezarykluczynski.stapi.server.series.common.AbstractEndpointIntegrationTest

abstract class AbstractComicCollectionEndpointIntegrationTest extends AbstractEndpointIntegrationTest {
}
