package com.cezarykluczynski.stapi.util

import com.cezarykluczynski.stapi.util.tool.LogicUtil

class AbstractStaffTest extends AbstractRealWorldPersonTest {

	protected static final boolean ART_DEPARTMENT = LogicUtil.nextBoolean()
	protected static final boolean ART_DIRECTOR = LogicUtil.nextBoolean()
	protected static final boolean PRODUCTION_DESIGNER = LogicUtil.nextBoolean()
	protected static final boolean CAMERA_AND_ELECTRICAL_DEPARTMENT = LogicUtil.nextBoolean()
	protected static final boolean CINEMATOGRAPHER = LogicUtil.nextBoolean()
	protected static final boolean CASTING_DEPARTMENT = LogicUtil.nextBoolean()
	protected static final boolean COSTUME_DEPARTMENT = LogicUtil.nextBoolean()
	protected static final boolean COSTUME_DESIGNER = LogicUtil.nextBoolean()
	protected static final boolean DIRECTOR = LogicUtil.nextBoolean()
	protected static final boolean ASSISTANT_AND_SECOND_UNIT_DIRECTOR = LogicUtil.nextBoolean()
	protected static final boolean EXHIBIT_AND_ATTRACTION_STAFF = LogicUtil.nextBoolean()
	protected static final boolean FILM_EDITOR = LogicUtil.nextBoolean()
	protected static final boolean LINGUIST = LogicUtil.nextBoolean()
	protected static final boolean LOCATION_STAFF = LogicUtil.nextBoolean()
	protected static final boolean MAKEUP_STAFF = LogicUtil.nextBoolean()
	protected static final boolean MUSIC_DEPARTMENT = LogicUtil.nextBoolean()
	protected static final boolean COMPOSER = LogicUtil.nextBoolean()
	protected static final boolean PERSONAL_ASSISTANT = LogicUtil.nextBoolean()
	protected static final boolean PRODUCER = LogicUtil.nextBoolean()
	protected static final boolean PRODUCTION_ASSOCIATE = LogicUtil.nextBoolean()
	protected static final boolean PRODUCTION_STAFF = LogicUtil.nextBoolean()
	protected static final boolean PUBLICATION_STAFF = LogicUtil.nextBoolean()
	protected static final boolean SCIENCE_CONSULTANT = LogicUtil.nextBoolean()
	protected static final boolean SOUND_DEPARTMENT = LogicUtil.nextBoolean()
	protected static final boolean SPECIAL_AND_VISUAL_EFFECTS_STAFF = LogicUtil.nextBoolean()
	protected static final boolean AUTHOR = LogicUtil.nextBoolean()
	protected static final boolean AUDIO_AUTHOR = LogicUtil.nextBoolean()
	protected static final boolean CALENDAR_ARTIST = LogicUtil.nextBoolean()
	protected static final boolean COMIC_ARTIST = LogicUtil.nextBoolean()
	protected static final boolean COMIC_AUTHOR = LogicUtil.nextBoolean()
	protected static final boolean COMIC_COLOR_ARTIST = LogicUtil.nextBoolean()
	protected static final boolean COMIC_INTERIOR_ARTIST = LogicUtil.nextBoolean()
	protected static final boolean COMIC_INK_ARTIST = LogicUtil.nextBoolean()
	protected static final boolean COMIC_PENCIL_ARTIST = LogicUtil.nextBoolean()
	protected static final boolean COMIC_LETTER_ARTIST = LogicUtil.nextBoolean()
	protected static final boolean COMIC_STRIP_ARTIST = LogicUtil.nextBoolean()
	protected static final boolean GAME_ARTIST = LogicUtil.nextBoolean()
	protected static final boolean GAME_AUTHOR = LogicUtil.nextBoolean()
	protected static final boolean NOVEL_ARTIST = LogicUtil.nextBoolean()
	protected static final boolean NOVEL_AUTHOR = LogicUtil.nextBoolean()
	protected static final boolean REFERENCE_ARTIST = LogicUtil.nextBoolean()
	protected static final boolean REFERENCE_AUTHOR = LogicUtil.nextBoolean()
	protected static final boolean PUBLICATION_ARTIST = LogicUtil.nextBoolean()
	protected static final boolean PUBLICATION_DESIGNER = LogicUtil.nextBoolean()
	protected static final boolean PUBLICATION_EDITOR = LogicUtil.nextBoolean()
	protected static final boolean PUBLICITY_ARTIST = LogicUtil.nextBoolean()
	protected static final boolean CBS_DIGITAL_STAFF = LogicUtil.nextBoolean()
	protected static final boolean ILM_PRODUCTION_STAFF = LogicUtil.nextBoolean()
	protected static final boolean SPECIAL_FEATURES_STAFF = LogicUtil.nextBoolean()
	protected static final boolean STORY_EDITOR = LogicUtil.nextBoolean()
	protected static final boolean STUDIO_EXECUTIVE = LogicUtil.nextBoolean()
	protected static final boolean STUNT_DEPARTMENT = LogicUtil.nextBoolean()
	protected static final boolean TRANSPORTATION_DEPARTMENT = LogicUtil.nextBoolean()
	protected static final boolean VIDEO_GAME_PRODUCTION_STAFF = LogicUtil.nextBoolean()
	protected static final boolean WRITER = LogicUtil.nextBoolean()

}
