package com.cezarykluczynski.stapi.client.api.rest

import com.cezarykluczynski.stapi.client.v1.rest.api.StaffApi
import com.cezarykluczynski.stapi.client.v1.rest.model.StaffBaseResponse
import com.cezarykluczynski.stapi.client.v1.rest.model.StaffFullResponse
import com.cezarykluczynski.stapi.client.v1.rest.model.StaffV2BaseResponse
import com.cezarykluczynski.stapi.client.v1.rest.model.StaffV2FullResponse
import com.cezarykluczynski.stapi.util.AbstractRealWorldPersonTest

class StaffTest extends AbstractRealWorldPersonTest {

	private StaffApi staffApiMock

	private Staff staff

	void setup() {
		staffApiMock = Mock()
		staff = new Staff(staffApiMock)
	}

	void "gets single entity"() {
		given:
		StaffFullResponse staffFullResponse = Mock()

		when:
		StaffFullResponse staffFullResponseOutput = staff.get(UID)

		then:
		1 * staffApiMock.v1RestStaffGet(UID, null) >> staffFullResponse
		0 * _
		staffFullResponse == staffFullResponseOutput
	}

	void "gets single entity (V2)"() {
		given:
		StaffV2FullResponse staffV2FullResponse = Mock()

		when:
		StaffV2FullResponse staffV2FullResponseOutput = staff.getV2(UID)

		then:
		1 * staffApiMock.v2RestStaffGet(UID) >> staffV2FullResponse
		0 * _
		staffV2FullResponse == staffV2FullResponseOutput
	}

	void "searches entities"() {
		given:
		StaffBaseResponse staffBaseResponse = Mock()

		when:
		StaffBaseResponse staffBaseResponseOutput = staff.search(PAGE_NUMBER, PAGE_SIZE, SORT, NAME, BIRTH_NAME, GENDER_STRING, DATE_OF_BIRTH_FROM,
				DATE_OF_BIRTH_TO, PLACE_OF_BIRTH, DATE_OF_DEATH_FROM, DATE_OF_DEATH_TO, PLACE_OF_DEATH, ART_DEPARTMENT, ART_DIRECTOR,
				PRODUCTION_DESIGNER, CAMERA_AND_ELECTRICAL_DEPARTMENT, CINEMATOGRAPHER, CASTING_DEPARTMENT, COSTUME_DEPARTMENT, COSTUME_DESIGNER,
				DIRECTOR, ASSISTANT_AND_SECOND_UNIT_DIRECTOR, EXHIBIT_AND_ATTRACTION_STAFF, FILM_EDITOR, LINGUIST, LOCATION_STAFF, MAKEUP_STAFF,
				MUSIC_DEPARTMENT, COMPOSER, PERSONAL_ASSISTANT, PRODUCER, PRODUCTION_ASSOCIATE, PRODUCTION_STAFF, PUBLICATION_STAFF,
				SCIENCE_CONSULTANT, SOUND_DEPARTMENT, SPECIAL_AND_VISUAL_EFFECTS_STAFF, AUTHOR, AUDIO_AUTHOR, CALENDAR_ARTIST, COMIC_ARTIST,
				COMIC_AUTHOR, COMIC_COLOR_ARTIST, COMIC_INTERIOR_ARTIST, COMIC_INK_ARTIST, COMIC_PENCIL_ARTIST, COMIC_LETTER_ARTIST,
				COMIC_STRIP_ARTIST, GAME_ARTIST, GAME_AUTHOR, NOVEL_ARTIST, NOVEL_AUTHOR, REFERENCE_ARTIST, REFERENCE_AUTHOR, PUBLICATION_ARTIST,
				PUBLICATION_DESIGNER, PUBLICATION_EDITOR, PUBLICITY_ARTIST, CBS_DIGITAL_STAFF, ILM_PRODUCTION_STAFF, SPECIAL_FEATURES_STAFF,
				STORY_EDITOR, STUDIO_EXECUTIVE, STUNT_DEPARTMENT, TRANSPORTATION_DEPARTMENT, VIDEO_GAME_PRODUCTION_STAFF, WRITER)

		then:
		1 * staffApiMock.v1RestStaffSearchPost(PAGE_NUMBER, PAGE_SIZE, SORT, null, NAME, BIRTH_NAME, GENDER_STRING, DATE_OF_BIRTH_FROM,
				DATE_OF_BIRTH_TO, PLACE_OF_BIRTH, DATE_OF_DEATH_FROM, DATE_OF_DEATH_TO, PLACE_OF_DEATH, ART_DEPARTMENT, ART_DIRECTOR,
				PRODUCTION_DESIGNER, CAMERA_AND_ELECTRICAL_DEPARTMENT, CINEMATOGRAPHER, CASTING_DEPARTMENT, COSTUME_DEPARTMENT, COSTUME_DESIGNER,
				DIRECTOR, ASSISTANT_AND_SECOND_UNIT_DIRECTOR, EXHIBIT_AND_ATTRACTION_STAFF, FILM_EDITOR, LINGUIST, LOCATION_STAFF, MAKEUP_STAFF,
				MUSIC_DEPARTMENT, COMPOSER, PERSONAL_ASSISTANT, PRODUCER, PRODUCTION_ASSOCIATE, PRODUCTION_STAFF, PUBLICATION_STAFF,
				SCIENCE_CONSULTANT, SOUND_DEPARTMENT, SPECIAL_AND_VISUAL_EFFECTS_STAFF, AUTHOR, AUDIO_AUTHOR, CALENDAR_ARTIST, COMIC_ARTIST,
				COMIC_AUTHOR, COMIC_COLOR_ARTIST, COMIC_INTERIOR_ARTIST, COMIC_INK_ARTIST, COMIC_PENCIL_ARTIST, COMIC_LETTER_ARTIST,
				COMIC_STRIP_ARTIST, GAME_ARTIST, GAME_AUTHOR, NOVEL_ARTIST, NOVEL_AUTHOR, REFERENCE_ARTIST, REFERENCE_AUTHOR, PUBLICATION_ARTIST,
				PUBLICATION_DESIGNER, PUBLICATION_EDITOR, PUBLICITY_ARTIST, CBS_DIGITAL_STAFF, ILM_PRODUCTION_STAFF, SPECIAL_FEATURES_STAFF,
				STORY_EDITOR, STUDIO_EXECUTIVE, STUNT_DEPARTMENT, TRANSPORTATION_DEPARTMENT, VIDEO_GAME_PRODUCTION_STAFF, WRITER) >> staffBaseResponse
		0 * _
		staffBaseResponse == staffBaseResponseOutput
	}

	void "searches entities (V2)"() {
		given:
		StaffV2BaseResponse staffV2BaseResponse = Mock()

		when:
		StaffV2BaseResponse staffBaseResponseOutput = staff.searchV2(PAGE_NUMBER, PAGE_SIZE, SORT, NAME, BIRTH_NAME, GENDER_STRING, DATE_OF_BIRTH_FROM,
				DATE_OF_BIRTH_TO, PLACE_OF_BIRTH, DATE_OF_DEATH_FROM, DATE_OF_DEATH_TO, PLACE_OF_DEATH, ART_DEPARTMENT, ART_DIRECTOR,
				PRODUCTION_DESIGNER, CAMERA_AND_ELECTRICAL_DEPARTMENT, CINEMATOGRAPHER, CASTING_DEPARTMENT, COSTUME_DEPARTMENT, COSTUME_DESIGNER,
				DIRECTOR, ASSISTANT_AND_SECOND_UNIT_DIRECTOR, EXHIBIT_AND_ATTRACTION_STAFF, FILM_EDITOR, FILMATION_PRODUCTION_STAFF, LINGUIST,
				LOCATION_STAFF, MAKEUP_STAFF, MERCHANDISE_STAFF, MUSIC_DEPARTMENT, COMPOSER, PERSONAL_ASSISTANT, PRODUCER, PRODUCTION_ASSOCIATE,
				PRODUCTION_STAFF, PUBLICATION_STAFF, SCIENCE_CONSULTANT, SOUND_DEPARTMENT, SPECIAL_AND_VISUAL_EFFECTS_STAFF, AUTHOR, AUDIO_AUTHOR,
				CALENDAR_ARTIST, COMIC_ARTIST, COMIC_AUTHOR, COMIC_COLOR_ARTIST, COMIC_COVER_ARTIST, COMIC_INTERIOR_ARTIST, COMIC_INK_ARTIST,
				COMIC_PENCIL_ARTIST, COMIC_LETTER_ARTIST, COMIC_STRIP_ARTIST, GAME_ARTIST, GAME_AUTHOR, NOVEL_ARTIST, NOVEL_AUTHOR, REFERENCE_ARTIST,
				REFERENCE_AUTHOR, PUBLICATION_ARTIST, PUBLICATION_DESIGNER, PUBLICATION_EDITOR, PUBLICITY_ARTIST, CBS_DIGITAL_STAFF,
				ILM_PRODUCTION_STAFF, SPECIAL_FEATURES_STAFF, STORY_EDITOR, STUDIO_EXECUTIVE, STUNT_DEPARTMENT, TRANSPORTATION_DEPARTMENT,
				VIDEO_GAME_PRODUCTION_STAFF, WRITER)

		then:
		1 * staffApiMock.v2RestStaffSearchPost(PAGE_NUMBER, PAGE_SIZE, SORT, NAME, BIRTH_NAME, GENDER_STRING, DATE_OF_BIRTH_FROM,
				DATE_OF_BIRTH_TO, PLACE_OF_BIRTH, DATE_OF_DEATH_FROM, DATE_OF_DEATH_TO, PLACE_OF_DEATH, ART_DEPARTMENT, ART_DIRECTOR,
				PRODUCTION_DESIGNER, CAMERA_AND_ELECTRICAL_DEPARTMENT, CINEMATOGRAPHER, CASTING_DEPARTMENT, COSTUME_DEPARTMENT, COSTUME_DESIGNER,
				DIRECTOR, ASSISTANT_AND_SECOND_UNIT_DIRECTOR, EXHIBIT_AND_ATTRACTION_STAFF, FILM_EDITOR, FILMATION_PRODUCTION_STAFF, LINGUIST,
				LOCATION_STAFF, MAKEUP_STAFF, MERCHANDISE_STAFF, MUSIC_DEPARTMENT, COMPOSER, PERSONAL_ASSISTANT, PRODUCER, PRODUCTION_ASSOCIATE,
				PRODUCTION_STAFF, PUBLICATION_STAFF, SCIENCE_CONSULTANT, SOUND_DEPARTMENT, SPECIAL_AND_VISUAL_EFFECTS_STAFF, AUTHOR, AUDIO_AUTHOR,
				CALENDAR_ARTIST, COMIC_ARTIST, COMIC_AUTHOR, COMIC_COLOR_ARTIST, COMIC_COVER_ARTIST, COMIC_INTERIOR_ARTIST, COMIC_INK_ARTIST,
				COMIC_PENCIL_ARTIST, COMIC_LETTER_ARTIST, COMIC_STRIP_ARTIST, GAME_ARTIST, GAME_AUTHOR, NOVEL_ARTIST, NOVEL_AUTHOR, REFERENCE_ARTIST,
				REFERENCE_AUTHOR, PUBLICATION_ARTIST, PUBLICATION_DESIGNER, PUBLICATION_EDITOR, PUBLICITY_ARTIST, CBS_DIGITAL_STAFF,
				ILM_PRODUCTION_STAFF, SPECIAL_FEATURES_STAFF, STORY_EDITOR, STUDIO_EXECUTIVE, STUNT_DEPARTMENT, TRANSPORTATION_DEPARTMENT,
				VIDEO_GAME_PRODUCTION_STAFF, WRITER) >> staffV2BaseResponse
		0 * _
		staffV2BaseResponse == staffBaseResponseOutput
	}

}
